### PR TITLE
Bug/fileman spool files

### LINKED ISSUE #44: Current implementation of spooling request bodies doesn't use the File Manager
Ideally, all file manipulation should stay in functions of the File Manager, to aim for cleaner code and reduce duplicated logic.

### PR DESCRIPTION
**Pull request by stellaaash**
This PR fixes some duplicate code in the connection manager and request parser, using code that was mostly already present in the File Manager.

### CODE REVIEW

File: src/ConnectionManager/Request.cpp [hunk 1]
```diff
@@ -123,53 +124,31 @@ void Request::set_error_status(HttpCode code) {
...
-            return false;
-        }
+    if (fd < 0 && errno != EEXIST) {
+        std::cerr << "[open_temp_body_file] failed to create unique temp file" << std::endl;
+        perror("[open_temp_body_file] - create_file");
+        return false;
     }
-
-    std::cerr << "[Request::open_temp_body_file] failed to create unique temp file\n";
-    return false;
```
Comment (stellaaash) [inline src/ConnectionManager/Request.cpp:172]: Butchered this one bad, will need a rewrite or a revert

File: src/ConnectionManager/Request.cpp [hunk 2]
```diff
@@ -203,7 +198,11 @@ bool Request::append_body_chunk(const char* data, size_t len) {
     }
 
     if (_is_body_spooled) {
-        if (!write_all(_body_fd, data, len)) return false;
+        // Use the length explicitely in case the data is binary and contains null bytes
```
Comment (0yech) [inline src/ConnectionManager/Request.cpp]:
```suggestion
        // Use the length explicitly in case the data is binary and contains null bytes
```
